#!/bin/bash    
#to run, modify permissions of the script with: chmod u+x launch.sh
echo "Fresh Install Automation Script"
sleep 2
sudo apt update 
yes | sudo apt upgrade   
yes | sudo apt install neofetch
yes | sudo apt install nmap   
yes | sudo apt install cmatrix
yes |sudo apt install cowsay
yes | sudo apt install kitty
yes | sudo apt install htop
neofetch
